# Generated by Django 4.2.11 on 2025-08-06 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todomodel",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 8, 6, 15, 23, 13, 317786, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
