# Generated by Django 4.2.11 on 2025-08-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todomodel_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="todomodel",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
